// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/noticias": {
    params: {};
  };
  "/noticias/:id": {
    params: {
      "id": string;
    };
  };
  "/favoritos": {
    params: {};
  };
  "/gestion": {
    params: {};
  };
  "/contacto": {
    params: {};
  };
  "/llms.txt": {
    params: {};
  };
  "/rss.xml": {
    params: {};
  };
  "/sitemap.xml": {
    params: {};
  };
  "/robots.txt": {
    params: {};
  };
  "/api/health": {
    params: {};
  };
  "/api/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/noticias" | "/noticias/:id" | "/favoritos" | "/gestion" | "/contacto" | "/llms.txt" | "/rss.xml" | "/sitemap.xml" | "/robots.txt" | "/api/health" | "/api/*";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/noticias.tsx": {
    id: "routes/noticias";
    page: "/noticias";
  };
  "routes/noticia.tsx": {
    id: "routes/noticia";
    page: "/noticias/:id";
  };
  "routes/favoritos.tsx": {
    id: "routes/favoritos";
    page: "/favoritos";
  };
  "routes/gestion.tsx": {
    id: "routes/gestion";
    page: "/gestion";
  };
  "routes/contacto.tsx": {
    id: "routes/contacto";
    page: "/contacto";
  };
  "routes/llms.txt.ts": {
    id: "routes/llms.txt";
    page: "/llms.txt";
  };
  "routes/rss.xml.ts": {
    id: "routes/rss.xml";
    page: "/rss.xml";
  };
  "routes/sitemap.xml.ts": {
    id: "routes/sitemap.xml";
    page: "/sitemap.xml";
  };
  "routes/robots.txt.ts": {
    id: "routes/robots.txt";
    page: "/robots.txt";
  };
  "routes/api.health.ts": {
    id: "routes/api.health";
    page: "/api/health";
  };
  "routes/api.$.ts": {
    id: "routes/api.$";
    page: "/api/*";
  };
};

type RouteModules = {
  "root": typeof import("./src/root.tsx");
  "routes/home": typeof import("./src/routes/home.tsx");
  "routes/noticias": typeof import("./src/routes/noticias.tsx");
  "routes/noticia": typeof import("./src/routes/noticia.tsx");
  "routes/favoritos": typeof import("./src/routes/favoritos.tsx");
  "routes/gestion": typeof import("./src/routes/gestion.tsx");
  "routes/contacto": typeof import("./src/routes/contacto.tsx");
  "routes/llms.txt": typeof import("./src/routes/llms.txt.ts");
  "routes/rss.xml": typeof import("./src/routes/rss.xml.ts");
  "routes/sitemap.xml": typeof import("./src/routes/sitemap.xml.ts");
  "routes/robots.txt": typeof import("./src/routes/robots.txt.ts");
  "routes/api.health": typeof import("./src/routes/api.health.ts");
  "routes/api.$": typeof import("./src/routes/api.$.ts");
};